// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let i = 0;
let fibo = 0;
let last1 = 1;
let last2 = 0;
let evenSum = 0;
do {

        // last2 + last1 = fibo
        fibo = last2 + last1;
        console.log(`${i}: ${last2} + ${last1} = ${fibo}`)

        if(fibo % 2 === 0)
        {
            evenSum = evenSum + fibo;
        }

        // next keys:
        last2 = last1;
        last1 = fibo;
    
    i++;
} while ( fibo < 4000000 )

console.log(`RESULT = ${evenSum}`)