/**
 * Highly divisible triangular number
 *
 * https://projecteuler.net/problem=12
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 * The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over
 * five hundred divisors?
 */

import logger from './logger.js';

import { divisors } from './helpers/index.js';

function problem0012() {
  const top = 500;
  let count = 0;
  let triangular = 0;
  let i = 1;

  while (count < top) {
    triangular += i;
    const d = divisors(triangular);

    logger.debug(`Triangular number: ${triangular} has ${d.length} divisors`);

    if (d.length > count) {
      count = d.length;
    }

    i += 1;
  }

  logger.info(`FOUND: ${count}`);

  return count;
}

export default problem0012;
export { problem0012 };
