---
name: Markdown Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

env:
  node-version: 26.x
  markdownlint-version: 0.49.1

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js ${{ env.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ env.node-version }}

      - name: Install tool
        run: >
          npm install -g --ignore-scripts
          markdownlint-cli@${{ env.markdownlint-version }}

      - name: Check tool
        run: >
          markdownlint --version

      - name: Lint
        run: >
          markdownlint --config .markdownlint.json '**/*.md'
          && echo '✔  Your code looks good.'
