---
name: Markdown Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Install dependencies
        run: >
          npm install -g --ignore-scripts markdownlint-cli@0.47.0

      - name: Test dependencies
        run: |
          markdownlint --version

      - name: Lint
        run: >
          markdownlint '**/*.md' --ignore node_modules
          && echo '✔  Your code looks good.'
