---
name: YAML lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    name: YAML lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: >
          yamllint --strict .
          && echo '✔  Your code looks good.'
